var CATEGORY_SCENERY = 0x0001;
var CATEGORY_PLAYER = 0x0002;
var CATEGORY_NPC = 0x0003;
var CATEGORY_NOCLIP = 0x0004;

var MASK_PLAYER = CATEGORY_SCENERY;
var MASK_NPC = CATEGORY_SCENERY;
var MASK_SCENERY = -1;
var MASK_NOCLIP = 99;